version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=userapidb
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456" ]
      interval: 5s       # check mỗi 5 giây
      timeout: 3s
      retries: 10        # thử 10 lần
    networks:
      - mynetwork
  app:
    image: i1
    depends_on:
      mysql: # service name
        condition: service_healthy  # ← chờ MySQL healthy hẳn mới start
    build:
      dockerfile: Dockerfile # dockerfile name
      context: . # thư mục hiện tại
    volumes:
      - .:/app                  # ← mount code thật vào container
      - /app/node_modules       # ← giữ node_modules của container, k bị ghi đè bởi node_modules bên host
    command: npx nodemon -L server.js  # ← tự restart khi sửa code #-L = Legacy Watch = nodemon tự kiểm tra file thay đổi định kỳ
    environment:
      - DB_HOST=mysql # service name, not container_name
      - DB_USER=root
      - DB_PASS=123456
    ports:
      - "3000:3000"
    restart: unless-stopped
    container_name: a1
    stdin_open: true
    tty: true
    networks:
      - mynetwork
networks:
  mynetwork:
    name: mynetwork
    driver: bridge
    # external: true # Dùng lại network được tạo sẵn